dir 'plugin_gems'
download "httpclient", "2.8.2.4"
download "td-client", "0.8.85"
download "td", "0.15.2"
download "fluent-plugin-td", "0.10.29"
download "thrift", "0.8.0"
download "fluent-plugin-scribe", "0.10.14"
download "uuidtools", "2.1.5"
download "bson", "1.12.5"
download "bson_ext", "1.12.5"
download "webhdfs", "0.8.0"
download "fluent-plugin-webhdfs", "0.4.2"
download "fluent-plugin-rewrite-tag-filter", "1.5.5"
download "fluent-plugin-td-monitoring", "0.2.2"
download "fluent-plugin-elasticsearch", "1.9.1"
